name = "CoHiRF"
uuid = "56071eaa-cbfc-4ef7-b235-902494ee9673"
version = "0.1.0"
authors = ["WilliBee <cbeng.william@gmail.com>"]

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ParallelKMeans = "42b8e9d4-006b-409a-8472-7f34b3fb58af"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Clustering = "0.15.8"
Distances = "0.10.12"
OrderedCollections = "1.8.1"
ParallelKMeans = "1.1.0"
Random = "1.11.0"
StatsBase = "0.34.8"
